[theme]
base = "light"
primaryColor = "#0F7B63"
backgroundColor = "#F3F5F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#15191C"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
